### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by igor-volgin** [zhengGroupDEV/mPSAT#1]
Dear developers,

Thank you very much for this nice tool. However, I cannot find the prebuild binary file. Also, an installation with build.py does not work since there is no onnxruntime_providers_shared.dll file in the tree. Could you please help me start using your tool?

Sincerely yours, 
Igor

**Comment by zhengGroupDEV** [comment]
Sure, if you click in to [Release](https://github.com/zhengGroupDEV/mPSAT/releases), you will find the prebuilt binaries and model weights were there.

**Comment by igor-volgin** [comment]
Thank you very much. I have not noticed this tab, sorry. GUI works well for PU.csv.
