### ISSUE TITLE
Questions about dataset for training

### ISSUE THREAD

**Issue by igor-volgin** [zhengGroupDEV/mPSAT#3]
Dear mPSAT developers,

We are currently trying to replicate the dataset collection procedure in order to understand which spectra from the works of Cowger and Back were included in the MPc dataset.
 
Since we have not found any information about direct correspondence between the spectra from the works of Cowger and Back and the spectra in MPc dataset, we have performed our own classification of the spectra by polymer types. During this procedure, we encountered several problems, which hardens replication of your results. Corresponding questions are detailed in the attached file below.

Also, we have faced with the presence of not normalized data in ds_mpc_mpb.ftr (https://github.com/zhengGroupDEV/mPSAT-backend/blob/master/data/ds_mpc_mpb.ftr). We assume they are from Back et al. work, but we need to be sure.  

We would greatly appreciate your comments on these questions! Your answers will help us correctly compare our results with those reported in your article.
 
Thank you in advance!

[questions_about_dataset.docx](https://github.com/user-attachments/files/17541874/questions_about_dataset.docx)

**Comment by zhengGroupDEV** [comment]
@igor-volgin Hi.

Are you the researcher who emailed to us? Didn't you receive our reply?

**Comment by zhengGroupDEV** [comment]
I will try to send you the email again, please reply to us if you received it.

**Comment by igor-volgin** [comment]
Yes, it's me. Thank you! Now I have revieved it.
